"""empty message

Revision ID: 19316f0734cd
Revises: b4aab732b15b
Create Date: 2018-12-17 13:33:34.909296

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '19316f0734cd'
down_revision = 'b4aab732b15b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('controller', sa.Column('date_updated', sa.DateTime(), nullable=True))
    op.add_column('order', sa.Column('date_updated', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('order', 'date_updated')
    op.drop_column('controller', 'date_updated')
    # ### end Alembic commands ###
