"""empty message

Revision ID: b4aab732b15b
Revises: 
Create Date: 2018-12-17 12:47:56.145296

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b4aab732b15b'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('customer',
    sa.Column('name', sa.String(length=120), nullable=True),
    sa.Column('email', sa.String(length=64), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('company', sa.String(length=120), nullable=True),
    sa.Column('phone', sa.String(length=20), nullable=True),
    sa.Column('address', sa.String(length=200), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_customer_email'), 'customer', ['email'], unique=True)
    op.create_index(op.f('ix_customer_name'), 'customer', ['name'], unique=False)
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=64), nullable=True),
    sa.Column('email', sa.String(length=120), nullable=True),
    sa.Column('password_hash', sa.String(length=128), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_email'), 'user', ['email'], unique=True)
    op.create_index(op.f('ix_user_username'), 'user', ['username'], unique=True)
    op.create_table('order',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('customer_id', sa.Integer(), nullable=True),
    sa.Column('bubble_six', sa.Integer(), nullable=False),
    sa.Column('bubble_nine', sa.Integer(), nullable=False),
    sa.Column('bubble_fourteen', sa.Integer(), nullable=False),
    sa.Column('puck_six', sa.Integer(), nullable=False),
    sa.Column('puck_molex_six', sa.Integer(), nullable=False),
    sa.Column('puck_nine', sa.Integer(), nullable=False),
    sa.Column('long_nineteen', sa.Integer(), nullable=False),
    sa.Column('short_nineteen', sa.Integer(), nullable=False),
    sa.Column('green_nineteen', sa.Integer(), nullable=False),
    sa.Column('ads_twentyfour', sa.Integer(), nullable=False),
    sa.Column('ads_thirtysix', sa.Integer(), nullable=False),
    sa.Column('two_forty', sa.Integer(), nullable=False),
    sa.Column('three_twenty', sa.Integer(), nullable=False),
    sa.Column('ride', sa.String(length=128), nullable=True),
    sa.Column('date_created', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['customer_id'], ['customer.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('controller',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('controller_number', sa.Integer(), nullable=True),
    sa.Column('order_id', sa.Integer(), nullable=True),
    sa.Column('customer_id', sa.Integer(), nullable=True),
    sa.Column('t_one_thousand', sa.Integer(), nullable=True),
    sa.Column('t_one_thousand_a', sa.Integer(), nullable=True),
    sa.Column('ym_four', sa.Integer(), nullable=True),
    sa.Column('ym_eight', sa.Integer(), nullable=True),
    sa.Column('falcon_two', sa.Integer(), nullable=True),
    sa.Column('falcon_four', sa.Integer(), nullable=True),
    sa.Column('falcon_sixteen', sa.Integer(), nullable=True),
    sa.Column('twentyfour_to_five', sa.Integer(), nullable=True),
    sa.Column('twentyfour_to_twelve', sa.Integer(), nullable=True),
    sa.Column('number_of_datas', sa.Integer(), nullable=True),
    sa.Column('raspberry_pi', sa.Integer(), nullable=True),
    sa.Column('tp_link', sa.Integer(), nullable=True),
    sa.Column('spokes', sa.Integer(), nullable=True),
    sa.Column('boxes', sa.String(), nullable=True),
    sa.Column('phoenix_one_by_one', sa.Integer(), nullable=True),
    sa.Column('phoenix_one_by_two', sa.Integer(), nullable=True),
    sa.Column('phoenix_two_by_two', sa.Integer(), nullable=True),
    sa.Column('date_created', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['customer_id'], ['customer.id'], ),
    sa.ForeignKeyConstraint(['order_id'], ['order.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('image',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('filename', sa.String(), nullable=True),
    sa.Column('url', sa.String(), nullable=True),
    sa.Column('controller_id', sa.Integer(), nullable=True),
    sa.Column('order_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['controller_id'], ['controller.id'], ),
    sa.ForeignKeyConstraint(['order_id'], ['order.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('image')
    op.drop_table('controller')
    op.drop_table('order')
    op.drop_index(op.f('ix_user_username'), table_name='user')
    op.drop_index(op.f('ix_user_email'), table_name='user')
    op.drop_table('user')
    op.drop_index(op.f('ix_customer_name'), table_name='customer')
    op.drop_index(op.f('ix_customer_email'), table_name='customer')
    op.drop_table('customer')
    # ### end Alembic commands ###
