"""empty message

Revision ID: 126e1ee33f8b
Revises: 6d3e88a9e4f9
Create Date: 2018-12-17 08:17:24.922077

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '126e1ee33f8b'
down_revision = '6d3e88a9e4f9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('controller', sa.Column('phoenix_one_by_one', sa.Integer(), nullable=True))
    op.add_column('controller', sa.Column('phoenix_one_by_two', sa.Integer(), nullable=True))
    op.add_column('controller', sa.Column('phoenix_two_by_two', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('controller', 'phoenix_two_by_two')
    op.drop_column('controller', 'phoenix_one_by_two')
    op.drop_column('controller', 'phoenix_one_by_one')
    # ### end Alembic commands ###
