"""empty message

Revision ID: 1a823c2ff890
Revises: b13bdbb2ac53
Create Date: 2018-12-06 06:42:36.680546

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1a823c2ff890'
down_revision = 'b13bdbb2ac53'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('customer',
    sa.Column('customer_name', sa.String(length=120), nullable=True),
    sa.Column('customer_email', sa.String(length=64), nullable=True),
    sa.Column('customer_id', sa.Integer(), nullable=False),
    sa.Column('customer_company', sa.String(length=120), nullable=True),
    sa.Column('customer_phone', sa.String(length=20), nullable=True),
    sa.Column('customer_address', sa.String(length=200), nullable=True),
    sa.PrimaryKeyConstraint('customer_id')
    )
    op.create_index(op.f('ix_customer_customer_email'), 'customer', ['customer_email'], unique=True)
    op.create_index(op.f('ix_customer_customer_name'), 'customer', ['customer_name'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_customer_customer_name'), table_name='customer')
    op.drop_index(op.f('ix_customer_customer_email'), table_name='customer')
    op.drop_table('customer')
    # ### end Alembic commands ###
