"""empty message

Revision ID: 3e8328e60398
Revises: 03d12de69db5
Create Date: 2018-12-06 15:22:54.004382

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3e8328e60398'
down_revision = '03d12de69db5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('order', sa.Column('three_twenty', sa.Boolean(), nullable=True))
    op.add_column('order', sa.Column('two_forty', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('order', 'two_forty')
    op.drop_column('order', 'three_twenty')
    # ### end Alembic commands ###
