"""empty message

Revision ID: 86473754696a
Revises: e8e44b08dcce
Create Date: 2018-12-11 11:46:26.926979

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '86473754696a'
down_revision = 'e8e44b08dcce'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('order', sa.Column('ride', sa.String(length=128), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('order', 'ride')
    # ### end Alembic commands ###
