"""empty message

Revision ID: e8993cfc36a0
Revises: 126e1ee33f8b
Create Date: 2018-12-17 08:23:56.491670

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e8993cfc36a0'
down_revision = '126e1ee33f8b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('controller', sa.Column('controller_number', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('controller', 'controller_number')
    # ### end Alembic commands ###
